# Generated by Django 5.0.7 on 2024-07-31 14:43

from django.db import migrations

# Add default categories to the database if they don't exist already
def add_default_categories(apps, schema_editor):
    Category = apps.get_model('quiz', 'Category')
    categories = [
        "General Knowledge", "Science", "History", "Sports", "Entertainment", "Geography"
    ]
    for category in categories:
        Category.objects.get_or_create(name=category)

class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_category'),
    ]

    operations = [
        migrations.RunPython(add_default_categories)
    ]
